### ISSUE TITLE
terra interface

### ISSUE THREAD

**Issue by rhijmans** [EvolEcolGroup/pastclim#23]
In `pastclim::time_bp`  you have 

```
if (x@ptr$timestep!="years"){
```

That breaks with the development version of terra. The @ptr$ methods are not really safe for use in other packages. Can you use the "official" interface instead? In this case that could be: 

```
if  (timeInfo(x)$step != "years"){
``` 

Thanks!

**Comment by dramanica** [comment]
@rhijmans You are right, that was sloppy. Guilty as charged! 
I have fixed it in `dev` branch, and made sure it was the only instance of using the @ptr approach.
