### ISSUE TITLE
match name of bio05/bio06 for Beyer/Krapp

### ISSUE THREAD

**Issue by TY-Cheng** [EvolEcolGroup/pastclim#35]
it was mentioned in the paper as 5/6 for min/max:
![image](https://github.com/EvolEcolGroup/pastclim/assets/14033617/3c398b9a-620d-4d8d-8c39-035f22fc10b7)
but in Krapp there is:
![image](https://github.com/EvolEcolGroup/pastclim/assets/14033617/1ee819aa-a9ab-4b5c-9caa-9118b31f3a04)
Maybe there could be a match?

**Comment by dramanica** [comment]
That's a typo in the table of the Beyer et al. 2020 paper. Looking at the data, bio05 is larger than bio06, as we would expect for the max vs min temperature (as one would expect from the standard definition of the variables: https://www.worldclim.org/data/bioclim.html):
`> bio_test<-region_slice(time_bp=0, bio_variables=c("bio05","bio06"),data="Beyer2020")
> summary(bio_test)
     bio05           bio06       
 Min.   : 1.00   Min.   :-59.20  
 1st Qu.:20.89   1st Qu.:-27.04  
 Median :28.51   Median : -5.89  
 Mean   :27.29   Mean   : -8.89  
 3rd Qu.:33.54   3rd Qu.:  9.09  
 Max.   :45.28   Max.   : 23.20  
 NA's   :73187   NA's   :73187   `

So, disregard the table in Beyer 2020 (we'll ask for a correction but it might take a little while), the data (and metadata) in `pastclim` are correct.

**Comment by TY-Cheng** [comment]
> That's a typo in the table of the Beyer et al. 2020 paper. Looking at the data, bio05 is larger than bio06, as we would expect for the max vs min temperature (as one would expect from the standard definition of the variables: https://www.worldclim.org/data/bioclim.html): `> bio_test<-region_slice(time_bp=0, bio_variables=c("bio05","bio06"),data="Beyer2020")
> 
> > summary(bio_test)
> > bio05           bio06
> > Min.   : 1.00   Min.   :-59.20
> > 1st Qu.:20.89   1st Qu.:-27.04
> > Median :28.51   Median : -5.89
> > Mean   :27.29   Mean   : -8.89
> > 3rd Qu.:33.54   3rd Qu.:  9.09
> > Max.   :45.28   Max.   : 23.20
> > NA's   :73187   NA's   :73187   `
> 
> So, disregard the table in Beyer 2020 (we'll ask for a correction but it might take a little while), the data (and metadata) in `pastclim` are correct.


Well noted. Thank you!
