### ISSUE TITLE
worldclim link broke

### ISSUE THREAD

**Issue by amrcode1** [EvolEcolGroup/pastclim#48]
Hi all, just a typo in the link for the worldclim present dataset

R/download_worldclim_present.R
Line 47:   base_url <- "https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1"

Should be:
base_url <- "https://geodata.ucdavis.edu/climate/worldclim/2_1/base/wc2.1"

I make a fork, reinstall the package and the download work!

Bests regards

**Comment by dramanica** [comment]
@amrcode1 Thank you for reporting this. the geodata server was down for a couple of days, and it has now changed some paths, as you found out. We'll try to issue a fix in the next couple of days.

**Comment by dramanica** [comment]
This is now fixed in `dev`.

**Comment by dramanica** [comment]
Version 2.1.0, which fixes this issue, is on its way to CRAN. Thank you @amrcode1 for reporting the issue.
