### ISSUE TITLE
Issue downloading Worldclim

### ISSUE THREAD

**Issue by Uriwolkow** [EvolEcolGroup/pastclim#51]
Hi!
I am trying to download worldclim data, and right after it reaches 100% I get this error. Tried running it again and no change. 
 I'm using the latest .dev version, 2.1.0

```
 [100%] Downloaded 49869449 bytes...
Error in eval(parse(text = file_details$download_function))(dataset = dataset,  : 
  something went wrong setting up this dataset
 the dataset will need downloading again
```

Best,
Uri

**Comment by dramanica** [comment]
Could you please provide me with the command that you are using (so that I know which variables and resolution you are trying to use?). The Worldclim server can be rather temperamental, so it might just be a question of retrying after a while. But if you send the command, I can check if the problem occurs over here as well.

**Comment by Uriwolkow** [comment]
I was just trying out the code from the basic vignette on my machine. 
The line producing the error was:
download_dataset(dataset = "WorldClim_2.1_10m")

**Comment by dramanica** [comment]
Hmm, this is puzzling. I just run it on my local machine, and tested it with our CI on github, and both are working. So, we need to figure out what is going wrong on your local machine. It might be an issue with the `gdal` library.
Can you please run the following test code:
```
  vrt_path <- file.path(tempdir(),"test.vrt")
  tif_files <- list.files(system.file("extdata/CHELSA_bio01", package="pastclim"),
             full.names = TRUE)
  # create the file
 sf::gdal_utils(
    util = "buildvrt",
    source = tif_files,
    destination = vrt_path,
    options = c("-separate","-overwrite")
  )
```

**Comment by Uriwolkow** [comment]
I ran this right now, with no errors. 
Then tried downloading WorldClim again, but failed. 
I should note that it did work with the Beyer2020 dataset.

**Comment by dramanica** [comment]
Ok, let's try something a bit more through. Could you please run the following set of tests?
```
library(testthat)
  vrt_path <- file.path(tempdir(),"test.vrt")
  tif_files <- list.files(system.file("extdata/CHELSA_bio01", package="pastclim"),
             full.names = TRUE)
  sf::gdal_utils(
    util = "buildvrt",
    source = tif_files,
    destination = vrt_path,
    options = c("-separate","-overwrite")
  )
  
  
  description <- "band_name_1"
  time_vector <- c(0,-10,-1000)
  expect_true(vrt_set_meta(vrt_path, description, time_vector))
  # check we have the correct description in the file
  vrt_rast <- terra::rast(vrt_path)
  expect_true(identical(names(vrt_rast),paste(description,time_vector, sep="_")))
  vrt_meta <- vrt_get_meta(vrt_path = vrt_path)
  expect_true(identical(vrt_meta$time_bp,time_vector))
  expect_true(identical(vrt_meta$description,description))
  # check that get_time_bp_steps works with a vrt file
  expect_true(identical(
    get_time_bp_steps(dataset="custom", path_to_nc = vrt_path),time_vector))
  
  
  # expect a warning if we try to set the metadata a second time
  expect_warning(vrt_res <- vrt_set_meta(vrt_path, description, time_vector),
               "metadata for pastclim is already present")
  expect_false(vrt_res)
  
  # expect a warning if we pass an incorrect number of times
  sf::gdal_utils(
    util = "buildvrt",
    source = tif_files,
    destination = vrt_path,
    options = c("-separate","-overwrite")
  )
  expect_warning(vrt_res <- vrt_set_meta(vrt_path, description, c(time_vector,4)),
                 "the vrt has a different number of")
  expect_false(vrt_res)
```
Also, could you please give me the output of:
`sf::sf_extSoftVersion()`

**Comment by Uriwolkow** [comment]
getting stuck on this one:
```
expect_true(vrt_set_meta(vrt_path, description, time_vector))
Error in vrt_set_meta(vrt_path, description, time_vector) : 
  could not find function "vrt_set_meta"
> expect_true(pastclim::vrt_set_meta(vrt_path, description, time_vector))
Error: 'vrt_set_meta' is not an exported object from 'namespace:pastclim'
```
also, like you asked:
```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
      "3.12.1"        "3.8.4"        "9.3.1"         "true"         "true"        "9.3.1"
```

**Comment by dramanica** [comment]
Sorry, my fault, I should have exposed the internal `pastclim` functions. Use this:
```
library(testthat)
vrt_path <- file.path(tempdir(),"test.vrt")
tif_files <- list.files(system.file("extdata/CHELSA_bio01", package="pastclim"),
                        full.names = TRUE)
sf::gdal_utils(
  util = "buildvrt",
  source = tif_files,
  destination = vrt_path,
  options = c("-separate","-overwrite")
)


description <- "band_name_1"
time_vector <- c(0,-10,-1000)
expect_true(pastclim:::vrt_set_meta(vrt_path, description, time_vector))
# check we have the correct description in the file
vrt_rast <- terra::rast(vrt_path)
expect_true(identical(names(vrt_rast),paste(description,time_vector, sep="_")))
vrt_meta <- pastclim:::vrt_get_meta(vrt_path = vrt_path)
expect_true(identical(vrt_meta$time_bp,time_vector))
expect_true(identical(vrt_meta$description,description))
# check that get_time_bp_steps works with a vrt file
expect_true(identical(
  pastclim:::get_time_bp_steps(dataset="custom", path_to_nc = vrt_path),time_vector))


# expect a warning if we try to set the metadata a second time
expect_warning(vrt_res <- pastclim:::vrt_set_meta(vrt_path, description, time_vector),
               "metadata for pastclim is already present")
expect_false(vrt_res)

# expect a warning if we pass an incorrect number of times
sf::gdal_utils(
  util = "buildvrt",
  source = tif_files,
  destination = vrt_path,
  options = c("-separate","-overwrite")
)
expect_warning(vrt_res <- pastclim:::vrt_set_meta(vrt_path, description, c(time_vector,4)),
               "the vrt has a different number of")
expect_false(vrt_res)
```
Also, what OS are you on? Thanks.

**Comment by Uriwolkow** [comment]
Now everything seems to be running ok. I'm using Windows 11

**Comment by dramanica** [comment]
Great, thanks for trying that. I have just checked our Windows 11 test machine, and it has exactly the same library versions as you, so it is surprising that yours does not work. 
If you are willing to do a bit more testing, I could create a debugging version of `pastclim` for you over the weekend so that we can chase down where things are going wrong on your machine.

**Comment by dramanica** [comment]
In the mean time, can you please share the output of:
`dir(get_data_path())`
If it includes "worldclim_2.1", then please also run:
`dir(paste0(get_data_path(),"/worldclim_2.1"))`
Finally, had you tried using the CRAN version before using `dev`?

**Comment by Uriwolkow** [comment]
Sure, we can try that. 
here is the output for these last two lines :
> dir(get_data_path())
 [1] "Beyer2020_annual_vars_v1.2.2.nc"    "example_climate_v1.3.0.nc"         
 [3] "worldclim_2.1"                      "WorldClim_2.1_10m_bio01_v1.4.0.vrt"
 [5] "WorldClim_2.1_10m_bio02_v1.4.0.vrt" "WorldClim_2.1_10m_bio03_v1.4.0.vrt"
 [7] "WorldClim_2.1_10m_bio04_v1.4.0.vrt" "WorldClim_2.1_10m_bio05_v1.4.0.vrt"
 [9] "WorldClim_2.1_10m_bio06_v1.4.0.vrt" "WorldClim_2.1_10m_bio07_v1.4.0.vrt"
[11] "WorldClim_2.1_10m_bio08_v1.4.0.vrt" "WorldClim_2.1_10m_bio09_v1.4.0.vrt"
[13] "WorldClim_2.1_10m_bio10_v1.4.0.vrt" "WorldClim_2.1_10m_bio11_v1.4.0.vrt"
[15] "WorldClim_2.1_10m_bio12_v1.4.0.vrt" "WorldClim_2.1_10m_bio13_v1.4.0.vrt"
[17] "WorldClim_2.1_10m_bio14_v1.4.0.vrt" "WorldClim_2.1_10m_bio15_v1.4.0.vrt"
[19] "WorldClim_2.1_10m_bio16_v1.4.0.vrt" "WorldClim_2.1_10m_bio17_v1.4.0.vrt"
[21] "WorldClim_2.1_10m_bio18_v1.4.0.vrt" "WorldClim_2.1_10m_bio19_v1.4.0.vrt"
> dir(paste0(get_data_path(),"/worldclim_2.1"))
[1] "wc2.1_10m_bio.zip"

I have the 2.0.0 version installedAnd tried using it vefore using 2.1.0. 
It printed a different error:
```
> download_dataset(dataset = "WorldClim_2.1_10m")
Error in curl::curl_download(full_url, destfile = destfile, quiet = FALSE) : 
  Timeout was reached: [] Send failure: Connection was aborted
```

**Comment by dramanica** [comment]
OK, I think I know what is going on. There was a crash when donwloading the data the first time, and it failed to clean after itself.
So, let's get rid of any old Worldclim file with:
```
unlink(paste0(get_data_path(),"/World*"))
unlink(paste0(get_data_path(),"/worldclim_2.1/*"))
```
Now rerun
```
dir(get_data_path())
```
And there should be no WorldClim*.vrt files. Then try to download "WorldClim" again.

**Comment by Uriwolkow** [comment]
I cleaned the .vrt files successfully, and tried downloading again.
I keep getting the curl error on the pastclim 2.0.0 version. 
And using 2.1.0, it started downloading, and again by 100% it produces the same fail error (even though I tried the 5m resolution this time)
```
download_dataset(dataset = "WorldClim_2.1_5m")
 [100%] Downloaded 179563774 bytes...
Error in eval(parse(text = file_details$download_function))(dataset = dataset,  : 
  something went wrong setting up this dataset
 the dataset will need downloading again
```

**Comment by dramanica** [comment]
Can you please post the content of the data dir?

**Comment by Uriwolkow** [comment]
these are the current contents, after the last download attempt:
```
> dir(get_data_path())
> list.files("C:/Users/University of Haifa/Documents/Uri_Albatross/Bubal_SDMs/models/data/pastclim")
 [1] "Beyer2020_annual_vars_v1.2.2.nc"   "example_climate_v1.3.0.nc"        
 [3] "worldclim_2.1"                     "WorldClim_2.1_5m_bio01_v1.4.0.vrt"
 [5] "WorldClim_2.1_5m_bio02_v1.4.0.vrt" "WorldClim_2.1_5m_bio03_v1.4.0.vrt"
 [7] "WorldClim_2.1_5m_bio04_v1.4.0.vrt" "WorldClim_2.1_5m_bio05_v1.4.0.vrt"
 [9] "WorldClim_2.1_5m_bio06_v1.4.0.vrt" "WorldClim_2.1_5m_bio07_v1.4.0.vrt"
[11] "WorldClim_2.1_5m_bio08_v1.4.0.vrt" "WorldClim_2.1_5m_bio09_v1.4.0.vrt"
[13] "WorldClim_2.1_5m_bio10_v1.4.0.vrt" "WorldClim_2.1_5m_bio11_v1.4.0.vrt"
[15] "WorldClim_2.1_5m_bio12_v1.4.0.vrt" "WorldClim_2.1_5m_bio13_v1.4.0.vrt"
[17] "WorldClim_2.1_5m_bio14_v1.4.0.vrt" "WorldClim_2.1_5m_bio15_v1.4.0.vrt"
[19] "WorldClim_2.1_5m_bio16_v1.4.0.vrt" "WorldClim_2.1_5m_bio17_v1.4.0.vrt"
[21] "WorldClim_2.1_5m_bio18_v1.4.0.vrt" "WorldClim_2.1_5m_bio19_v1.4.0.vrt"
```

**Comment by dramanica** [comment]
Ok. Just out of curiosity, what happens if you try to use the dataset.

**Comment by Uriwolkow** [comment]
"aware" of its existence or expecting it, but unavailable:
```
> land_mask <-
+   get_land_mask(time_ce = 1985, dataset = "WorldClim_2.1_5m") # Edited this from 1985 Worldclim to 1950 Beyer2020, 24.6.24
Error in check_var_downloaded(bio_variables, dataset) : 
  variable (bio01) not yet downloaded, use `download_dataset()`

```

**Comment by dramanica** [comment]
Ok, this is really strange, as we can see the bio01 file in your data path. Would you be willing to Zoom so that we can try a few things live? Send me an email on am315@cam.ac.uk and we can set up a session next week to get to the bottom of this strange behaviour.
Also, what do you get if you type:
`Sys.getlocale()`

**Comment by dramanica** [comment]
Note for future similar issues: This was due to a failed upgrade of the package which had left a messed up environment. A clean update eventually solved the problem.

**Comment by SamuelWatsonii** [comment]
Hello, I’m experiencing the exact same issue when trying to use download_dataset() for WorldClim_2.1_ACCESS-CM2_ssp126_5m and other resolutions (2.5m, 0.5m). The 10m version works fine, but the others return this error:

`Error in eval(parse(text = file_details$download_function))(dataset = dataset, : 
something went wrong downloading the data; try again`

For present climate datasets, I'm able to download all spatial resolutions (10m, 5m, 2.5m, 0.5m) without any problem.
However, when I try to download future climate datasets, the error appears for all higher resolutions (5m, 2.5m, and 0.5m).

I updated the pastclim package and restarted RStudio, but the error continues. I saw in this thread that the issue was related to a "failed upgrade" and was solved by a clean update. Could you please explain how that clean update was done? I want to try the same solution.

Thank you very much for your help!

**Comment by dramanica** [comment]
@SamuelWatsonii Can you please try setting the data path with `set_data_path()` to a new directory, and redownloading the datasets (one that didn't work and one that did?).

**Comment by SamuelWatsonii** [comment]
Yes, I am able to download all spatial resolutions for present climate data: "WorldClim_2.1_0.5m", "WorldClim_2.1_2.5m", "WorldClim_2.1_5m", "WorldClim_2.1_10m"

However, for future climate scenarios, I can only successfully download the 10m resolution datasets (WorldClim_2.1_ACCESS-CM2_ssp126_10m, ssp245_10m, ssp370_10m, and ssp585_10m)

The other resolutions (5m, 2.5m, and 0.5m) for all SSP scenarios fail to download with the error message mentioned earlier. I've tried the suggested solutions but continue experiencing the same issue

```
> set_data_path(
+   path_to_nc = 'data/pastclim',
+   ask = TRUE,
+   write_config = TRUE,
+   copy_example = TRUE,
+   on_CRAN = FALSE
+ )
The data_path will be set to D:\MCRN\TESIS MAESTRIA\MODELACION_BTS\data\pastclim.
A copy of the Example dataset will be copied there.
This path will be saved by pastclim for future use.
Proceed? 

1: Yes
2: No

Selection: 1
[1] TRUE
> download_dataset("WorldClim_2.1_ACCESS-CM2_ssp126_10m")
Download status: 4 done; 0 in progress. Total size: 133.51 Mb (100%)... done!             
[1] TRUE
> download_dataset("WorldClim_2.1_ACCESS-CM2_ssp126_5m")
Download status: 4 done; 0 in progress. Total size: 250.94 Mb (100%)... done!             
Error en eval(parse(text = file_details$download_function))(dataset = dataset, : 
  something went wrong downloading the data; try again
```

Then:

```
> list.files("data/pastclim")
 [1] "example_climate_v1.3.0.nc"                           
 [2] "worldclim_2.1"                                       
 [3] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio01_v2.0.0.vrt"
 [4] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio02_v2.0.0.vrt"
 [5] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio03_v2.0.0.vrt"
 [6] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio04_v2.0.0.vrt"
 [7] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio05_v2.0.0.vrt"
 [8] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio06_v2.0.0.vrt"
 [9] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio07_v2.0.0.vrt"
[10] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio08_v2.0.0.vrt"
[11] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio09_v2.0.0.vrt"
[12] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio10_v2.0.0.vrt"
[13] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio11_v2.0.0.vrt"
[14] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio12_v2.0.0.vrt"
[15] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio13_v2.0.0.vrt"
[16] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio14_v2.0.0.vrt"
[17] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio15_v2.0.0.vrt"
[18] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio16_v2.0.0.vrt"
[19] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio17_v2.0.0.vrt"
[20] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio18_v2.0.0.vrt"
[21] "WorldClim_2.1_ACCESS-CM2_ssp126_10m_bio19_v2.0.0.vrt"
```

Session info:

```
> sessionInfo()
R version 4.4.2 (2024-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)
```

**Comment by dramanica** [comment]
@SamuelWatsonii Ok, this is a tricky one. The error comes from `curl::multi_download()` reporting that it failed to successfully download the files. We can see that the file names were correct, as the downloads did happen (I also just downloaded that dataset without problems in my machine), but something went wrong when reporting whether the files were downloaded correctly.
Just to check before we go further, you do have plenty of space on your harddrive (i.e. we are not having problems with running out of space, as the other resolutions are somewhat large files). If you do, could you please go on the WorldClim website and download manually one of the relevant files to check that you can correctly download via another mean? Once we have confirmed those two things, I can start creating a debug version of `pastclim` so that we can get more information on the nature of the failure you are experiencing.
